"use client";

import { useState } from "react";
import { CircleDollarSign, ClipboardCheck, Database, HeartHandshake, LayoutDashboard, RefreshCw, Trophy, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { createOrUpdateCharityAction, setCharityActiveAction, createCharityEventAction, deleteCharityEventAction, createDrawAction, simulateDrawAction, publishDrawAction, cancelDrawAction, reviewWinnerAction, markWinnerPaidAction } from "@/lib/admin/actions";

type AdminData = Awaited<ReturnType<typeof import("@/lib/admin/operations").getAdminData>>;
type Overview = Awaited<ReturnType<typeof import("@/lib/admin/operations").getAdminOverview>>;
type Tab = "overview" | "users" | "billing" | "scores" | "draws" | "charities" | "winners";
const tabs: Array<{ id: Tab; label: string; icon: typeof LayoutDashboard }> = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "users", label: "Users", icon: Users }, { id: "billing", label: "Subscriptions", icon: CircleDollarSign }, { id: "scores", label: "Scores", icon: Database }, { id: "draws", label: "Draws", icon: Trophy }, { id: "charities", label: "Charities", icon: HeartHandshake }, { id: "winners", label: "Winners & payouts", icon: ClipboardCheck }];
function money(minor: number, currency = "GBP") { return new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(Number(minor || 0) / 100); }
function date(value: string | null | undefined) { return value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—"; }
function statusVariant(status: string): "default" | "secondary" | "outline" | "destructive" { if (["active", "approved", "paid", "published"].includes(status)) return "default"; if (["rejected", "cancelled", "failed"].includes(status)) return "destructive"; if (["pending", "submitted", "under_review", "simulated"].includes(status)) return "secondary"; return "outline"; }
export function AdminDashboard({ data, overview }: { data: AdminData; overview: Overview }) { const [tab, setTab] = useState<Tab>("overview"); const [charityId, setCharityId] = useState<string | null>(null); return <div className="min-h-screen bg-[#f7f8f5]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Digital Heroes</p><h1 className="text-2xl font-semibold">Administration</h1></div><form action="/login"><Button variant="outline" type="submit">Return to login</Button></form></div></header><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-6 lg:flex-row"><aside className="lg:w-56"><nav className="flex gap-1 overflow-x-auto rounded-xl border bg-white p-2 lg:block">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium lg:w-full ${tab === id ? "bg-emerald-700 text-white" : "text-slate-600 hover:bg-slate-100"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav></aside><main className="min-w-0 flex-1 space-y-6">{tab === "overview" && <OverviewPanel overview={overview} data={data} />}{tab === "users" && <TablePanel title="Users"><table className="w-full text-sm"><tbody>{data.users.map(u => <tr key={u.id} className="border-b"><td className="p-2">{u.full_name || "Unnamed user"}</td><td className="p-2">{u.role}</td><td className="p-2">{u.charity_contribution_percentage}%</td><td className="p-2">{date(u.created_at)}</td></tr>)}</tbody></table></TablePanel>}{tab === "billing" && <TablePanel title="Subscriptions"><table className="w-full text-sm"><tbody>{data.subscriptions.map(s => <tr key={s.id} className="border-b"><td className="p-2 font-mono text-xs">{s.user_id}</td><td className="p-2 capitalize">{s.plan_interval}</td><td className="p-2"><Badge variant={statusVariant(s.status)}>{s.status}</Badge></td><td className="p-2">{money(s.unit_amount_minor, s.currency)}</td><td className="p-2">{date(s.current_period_end)}</td></tr>)}</tbody></table></TablePanel>}{tab === "scores" && <TablePanel title="Golf scores"><table className="w-full text-sm"><tbody>{data.scores.map(s => <tr key={s.id} className="border-b"><td className="p-2 font-mono text-xs">{s.user_id}</td><td className="p-2">{date(s.score_date)}</td><td className="p-2"><Badge>{s.stableford_score}</Badge></td></tr>)}</tbody></table></TablePanel>}{tab === "draws" && <DrawsPanel data={data} />}{tab === "charities" && <CharitiesPanel data={data} editingId={charityId} setEditingId={setCharityId} />}{tab === "winners" && <WinnersPanel data={data} />}</main></div></div>; }
function TablePanel({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><div className="overflow-x-auto">{children}</div></CardContent></Card>; }
function Stat({ label, value, hint }: { label: string; value: string | number; hint?: string }) { return <Card><CardContent className="pt-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</CardContent></Card>; }
function OverviewPanel({ overview, data }: { overview: Overview; data: AdminData }) { return <><div><h2 className="text-xl font-semibold">Platform overview</h2><p className="text-sm text-muted-foreground">Subscriptions, scores, draws and charity impact.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total users" value={overview.total_users} /><Stat label="Active subscriptions" value={overview.active_subscriptions} /><Stat label="Active charities" value={overview.active_charities} /><Stat label="Pending winners" value={overview.pending_winners} /></div><div className="grid gap-4 lg:grid-cols-3"><Stat label="Subscription charity contributions" value={money(overview.subscription_contributions_minor)} /><Stat label="Independent donations" value={money(overview.donation_total_minor)} /><Stat label="Prize pools" value={data.pools.length} hint={`Rollover ${money(overview.rollover_in_minor)}`} /></div></>; }
function DrawsPanel({ data }: { data: AdminData }) { return <div className="space-y-6"><Card><CardHeader><CardTitle>Create monthly draw</CardTitle><CardDescription>Draft → simulate → publish.</CardDescription></CardHeader><CardContent><form action={createDrawAction} className="grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><div><Label>Month</Label><Input name="draw_month" type="month" required /></div><div><Label>Type</Label><select name="type" defaultValue="random" className="h-8 w-full rounded-lg border px-2"><option value="random">Random</option><option value="algorithmic">Algorithmic</option></select></div><div className="flex items-end"><Button type="submit">Create draft</Button></div></form></CardContent></Card><Card><CardHeader><CardTitle>Draw lifecycle</CardTitle></CardHeader><CardContent className="space-y-4">{data.draws.map(d => <div key={d.id} className="rounded-xl border p-4"><div className="flex items-center justify-between"><div><p className="font-semibold">{date(d.draw_month)} · {d.type}</p>{d.numbers && <div className="mt-2 flex flex-wrap gap-2">{d.numbers.map((n: number) => <Badge key={n} variant="outline">{n}</Badge>)}</div>}</div><Badge variant={statusVariant(d.status)}>{d.status}</Badge></div>{(d.status === "draft" || d.status === "simulated") && <div className="mt-3 flex gap-2"><form action={simulateDrawAction}><input type="hidden" name="draw_id" value={d.id} /><Button size="sm" type="submit"><RefreshCw className="mr-1 h-3 w-3" />Simulate</Button></form>{d.status === "simulated" && <form action={publishDrawAction}><input type="hidden" name="draw_id" value={d.id} /><Button size="sm" type="submit">Publish</Button></form>}<form action={cancelDrawAction}><input type="hidden" name="draw_id" value={d.id} /><Button size="sm" variant="outline" type="submit">Cancel</Button></form></div>}</div>)}</CardContent></Card></div>; }
function CharitiesPanel({ data, editingId, setEditingId }: { data: AdminData; editingId: string | null; setEditingId: (id: string | null) => void }) { const editing = data.charities.find(c => c.id === editingId); return <div className="space-y-6"><Card><CardHeader><CardTitle>{editing ? "Edit charity" : "Add charity"}</CardTitle></CardHeader><CardContent><form action={createOrUpdateCharityAction} className="grid gap-4"><input type="hidden" name="id" value={editing?.id || ""} /><div className="grid gap-4 sm:grid-cols-2"><div><Label>Name</Label><Input name="name" required defaultValue={editing?.name || ""} /></div><div><Label>Slug</Label><Input name="slug" required defaultValue={editing?.slug || ""} /></div></div><div><Label>Short description</Label><Input name="short_description" required defaultValue={editing?.short_description || ""} /></div><div><Label>Description</Label><Textarea name="description" required defaultValue={editing?.description || ""} /></div><div className="grid gap-4 sm:grid-cols-2"><Input name="website_url" type="url" placeholder="Website" defaultValue={editing?.website_url || ""} /><Input name="image_path" placeholder="Image path" defaultValue={editing?.image_path || ""} /></div><div className="flex gap-5 text-sm"><label><input type="checkbox" name="is_featured" defaultChecked={editing?.is_featured || false} /> Featured</label><label><input type="checkbox" name="is_active" defaultChecked={editing ? editing.is_active : true} /> Active</label></div><Button type="submit">{editing ? "Save changes" : "Create charity"}</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Charities & events</CardTitle></CardHeader><CardContent className="space-y-3">{data.charities.map(c => <div key={c.id} className="flex items-center justify-between border-b py-2"><span>{c.name}</span><div className="flex gap-2"><Button size="sm" variant="outline" type="button" onClick={() => setEditingId(c.id)}>Edit</Button><form action={setCharityActiveAction}><input type="hidden" name="charity_id" value={c.id} /><input type="hidden" name="active" value={String(!c.is_active)} /><Button size="sm" variant="outline" type="submit">{c.is_active ? "Deactivate" : "Activate"}</Button></form></div></div>)}{data.events.map(e => <div key={e.id} className="flex items-center justify-between border-b py-2"><span>{e.title}</span><form action={deleteCharityEventAction}><input type="hidden" name="event_id" value={e.id} /><Button size="sm" variant="outline" type="submit">Delete</Button></form></div>)}<form action={createCharityEventAction} className="grid gap-3 sm:grid-cols-3"><select name="charity_id" required className="h-9 rounded border px-2"><option value="">Charity</option>{data.charities.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><Input name="title" placeholder="Event title" required /><Input name="event_date" type="date" required /><Button type="submit">Add event</Button></form></CardContent></Card></div>; }
function WinnersPanel({ data }: { data: AdminData }) { return <Card><CardHeader><CardTitle>Winner verification & payouts</CardTitle></CardHeader><CardContent className="space-y-4">{data.winners.map(w => <div key={w.id} className="rounded-xl border p-4"><div className="flex justify-between"><span>Tier {w.tier} · {money(w.prize_amount_minor)}</span><Badge variant={statusVariant(w.verification_status)}>{w.verification_status}</Badge></div><p className="mt-2 text-sm">Proofs: {w.winner_proofs.length} · Payout: {w.payouts[0]?.status || "not created"}</p><div className="mt-3 flex gap-2"><form action={reviewWinnerAction}><input type="hidden" name="winner_id" value={w.id} /><input type="hidden" name="decision" value="approved" /><Button size="sm" type="submit">Approve</Button></form><form action={reviewWinnerAction}><input type="hidden" name="winner_id" value={w.id} /><input type="hidden" name="decision" value="rejected" /><input type="hidden" name="reason" value="Proof rejected by administrator" /><Button size="sm" variant="outline" type="submit">Reject</Button></form>{w.verification_status === "approved" && <form action={markWinnerPaidAction}><input type="hidden" name="winner_id" value={w.id} /><Button size="sm" type="submit">Mark paid</Button></form>}</div></div>)}</CardContent></Card>; }
