"use client";

import { useState } from "react";
import { BarChart3, CalendarDays, ChevronDown, CircleDollarSign, ClipboardCheck, Database, HeartHandshake, LayoutDashboard, RefreshCw, Trophy, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  createOrUpdateCharityAction, setCharityActiveAction, createCharityEventAction, deleteCharityEventAction,
  uploadCharityMediaAction, createDrawAction, simulateDrawAction, publishDrawAction, cancelDrawAction,
  reviewWinnerAction, markWinnerPaidAction,
} from "@/lib/admin/actions";

type AdminData = Awaited<ReturnType<typeof import("@/lib/admin/operations").getAdminData>>;
type Overview = Awaited<ReturnType<typeof import("@/lib/admin/operations").getAdminOverview>>;

type Tab = "overview" | "users" | "billing" | "scores" | "draws" | "charities" | "winners";

const tabs: Array<{ id: Tab; label: string; icon: typeof LayoutDashboard }> = [
  { id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "users", label: "Users", icon: Users },
  { id: "billing", label: "Subscriptions", icon: CircleDollarSign }, { id: "scores", label: "Scores", icon: Database },
  { id: "draws", label: "Draws", icon: Trophy }, { id: "charities", label: "Charities", icon: HeartHandshake }, { id: "winners", label: "Winners & payouts", icon: ClipboardCheck },
];

function money(minor: number, currency = "GBP") { return new Intl.NumberFormat("en-GB", { style: "currency", currency }).format(Number(minor || 0) / 100); }
function date(value: string | null | undefined) { return value ? new Date(value).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }) : "—"; }
function statusVariant(status: string): "default" | "secondary" | "outline" | "destructive" { if (["active", "approved", "paid", "published"].includes(status)) return "default"; if (["rejected", "cancelled", "failed"].includes(status)) return "destructive"; if (["pending", "submitted", "under_review", "simulated"].includes(status)) return "secondary"; return "outline"; }

export function AdminDashboard({ data, overview }: { data: AdminData; overview: Overview }) {
  const [tab, setTab] = useState<Tab>("overview");
  const [charityId, setCharityId] = useState<string | null>(null);

  return (
    <div className="min-h-screen bg-[#f7f8f5]">
      <header className="border-b bg-white/90 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-5 sm:px-6 lg:px-8">
          <div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Digital Heroes</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Administration</h1></div>
          <form action="/login"><Button variant="outline" type="submit">Return to login</Button></form>
        </div>
      </header>
      <div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-6 sm:px-6 lg:flex-row lg:px-8">
        <aside className="lg:w-56 lg:shrink-0"><nav className="flex gap-1 overflow-x-auto rounded-xl border bg-white p-2 lg:block lg:space-y-1 lg:overflow-visible">
          {tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition-colors lg:w-full ${tab === id ? "bg-emerald-700 text-white" : "text-slate-600 hover:bg-slate-100"}`}><Icon className="h-4 w-4" />{label}</button>)}
        </nav></aside>
        <main className="min-w-0 flex-1 space-y-6">
          {tab === "overview" && <OverviewPanel overview={overview} data={data} />}
          {tab === "users" && <UsersPanel data={data} />}
          {tab === "billing" && <SubscriptionsPanel data={data} />}
          {tab === "scores" && <ScoresPanel data={data} />}
          {tab === "draws" && <DrawsPanel data={data} />}
          {tab === "charities" && <CharitiesPanel data={data} editingId={charityId} setEditingId={setCharityId} />}
          {tab === "winners" && <WinnersPanel data={data} />}
        </main>
      </div>
    </div>
  );
}

function Stat({ label, value, hint }: { label: string; value: string | number; hint?: string }) { return <Card><CardContent className="pt-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p>{hint && <p className="mt-1 text-xs text-muted-foreground">{hint}</p>}</CardContent></Card>; }

function OverviewPanel({ overview, data }: { overview: Overview; data: AdminData }) {
  return <>
    <div><h2 className="text-xl font-semibold">Platform overview</h2><p className="mt-1 text-sm text-muted-foreground">Operational snapshot across subscriptions, scores, draws and charity impact.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total users" value={overview.total_users} /><Stat label="Active subscriptions" value={overview.active_subscriptions} /><Stat label="Active charities" value={overview.active_charities} /><Stat label="Pending winners" value={overview.pending_winners} /></div>
    <div className="grid gap-4 lg:grid-cols-3"><Stat label="Subscription charity contributions" value={money(overview.subscription_contributions_minor)} /><Stat label="Independent donations" value={money(overview.donation_total_minor)} /><Stat label="Prize pools created" value={data.pools.length} hint={`Rollover in ${money(overview.rollover_in_minor)}`} /></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5" />System health</CardTitle><CardDescription>Counts from the current Supabase data.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Users</p><p className="mt-1 font-semibold">{overview.total_users}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Golf scores</p><p className="mt-1 font-semibold">{overview.scores}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">Draws</p><p className="mt-1 font-semibold">{data.draws.length}</p></div></CardContent></Card>
  </>;
}

function UsersPanel({ data }: { data: AdminData }) { return <Card><CardHeader><CardTitle>Users</CardTitle><CardDescription>Latest subscriber and administrator profiles.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Name</th><th className="p-2">Role</th><th className="p-2">Charity</th><th className="p-2">Contribution</th><th className="p-2">Joined</th></tr></thead><tbody>{data.users.map((u) => <tr key={u.id} className="border-b last:border-0"><td className="p-2 font-medium">{u.full_name || "Unnamed user"}<span className="block max-w-[180px] truncate text-xs text-muted-foreground">{u.id}</span></td><td className="p-2"><Badge variant="outline">{u.role}</Badge></td><td className="p-2">{data.charities.find(c => c.id === u.preferred_charity_id)?.name || "Not selected"}</td><td className="p-2">{u.charity_contribution_percentage}%</td><td className="p-2">{date(u.created_at)}</td></tr>)}</tbody></table></div></CardContent></Card>; }

function SubscriptionsPanel({ data }: { data: AdminData }) { return <Card><CardHeader><CardTitle>Subscriptions</CardTitle><CardDescription>Stripe-backed subscription records and lifecycle state.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">User</th><th className="p-2">Plan</th><th className="p-2">Status</th><th className="p-2">Amount</th><th className="p-2">Period end</th><th className="p-2">Cancellation</th></tr></thead><tbody>{data.subscriptions.map(s => <tr key={s.id} className="border-b last:border-0"><td className="p-2 font-mono text-xs">{s.user_id}</td><td className="p-2 capitalize">{s.plan_interval}</td><td className="p-2"><Badge variant={statusVariant(s.status)}>{s.status}</Badge></td><td className="p-2">{money(s.unit_amount_minor, s.currency)}</td><td className="p-2">{date(s.current_period_end)}</td><td className="p-2">{s.cancel_at_period_end ? "Scheduled" : "—"}</td></tr>)}</tbody></table></div></CardContent></Card>; }

function ScoresPanel({ data }: { data: AdminData }) { return <Card><CardHeader><CardTitle>Golf scores</CardTitle><CardDescription>Latest score records across subscribers.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">User</th><th className="p-2">Date</th><th className="p-2">Stableford</th><th className="p-2">Created</th></tr></thead><tbody>{data.scores.map(s => <tr key={s.id} className="border-b last:border-0"><td className="p-2 font-mono text-xs">{s.user_id}</td><td className="p-2">{date(s.score_date)}</td><td className="p-2"><Badge>{s.stableford_score}</Badge></td><td className="p-2">{date(s.created_at)}</td></tr>)}</tbody></table></div></CardContent></Card>; }

function DrawsPanel({ data }: { data: AdminData }) {
  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>Create monthly draw</CardTitle><CardDescription>Create a draft, then simulate it before publishing.</CardDescription></CardHeader><CardContent><form action={createDrawAction} className="grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><div className="space-y-2"><Label htmlFor="draw-month">Month</Label><Input id="draw-month" name="draw_month" type="month" required /></div><div className="space-y-2"><Label htmlFor="draw-type">Draw type</Label><select id="draw-type" name="type" defaultValue="random" className="h-8 w-full rounded-lg border border-input bg-transparent px-2.5 text-sm"><option value="random">Random</option><option value="algorithmic">Algorithmic</option></select></div><div className="flex items-end"><Button type="submit">Create draft</Button></div></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Draw lifecycle</CardTitle><CardDescription>Published draws are immutable. Simulation is kept separate from production results.</CardDescription></CardHeader><CardContent className="space-y-4">{data.draws.length === 0 ? <p className="text-sm text-muted-foreground">No draws yet.</p> : data.draws.map(d => <div key={d.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{date(d.draw_month)} · {d.type}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{d.id}</p>{d.numbers && <div className="mt-3 flex flex-wrap gap-2">{d.numbers.map(n => <Badge key={n} variant="outline">{n}</Badge>)}</div>}</div><Badge variant={statusVariant(d.status)}>{d.status}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{(d.status === "draft" || d.status === "simulated") && <><form action={simulateDrawAction}><input type="hidden" name="draw_id" value={d.id} /><input name="seed" placeholder="Optional simulation seed" className="h-8 rounded-lg border px-2 text-xs" /><Button size="sm" type="submit"><RefreshCw className="mr-1 h-3.5 w-3.5" />Simulate</Button></form>{d.status === "simulated" && <form action={publishDrawAction}><input type="hidden" name="draw_id" value={d.id} /><Button size="sm" type="submit">Publish</Button></form>}<form action={cancelDrawAction}><input type="hidden" name="draw_id" value={d.id} /><Button size="sm" variant="outline" type="submit">Cancel</Button></form></>}{d.status === "published" && <span className="text-xs text-muted-foreground">Published {date(d.published_at)}</span>}</div></div>)}</CardContent></Card>
  </div>;
}

function CharitiesPanel({ data, editingId, setEditingId }: { data: AdminData; editingId: string | null; setEditingId: (id: string | null) => void }) {
  const editing = data.charities.find(c => c.id === editingId);
  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>{editing ? "Edit charity" : "Add charity"}</CardTitle><CardDescription>Manage public charity content and activation.</CardDescription></CardHeader><CardContent><form action={createOrUpdateCharityAction} className="grid gap-4"><input type="hidden" name="id" value={editing?.id || ""} /><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Name</Label><Input name="name" required defaultValue={editing?.name || ""} /></div><div className="space-y-2"><Label>Slug</Label><Input name="slug" required defaultValue={editing?.slug || ""} /></div></div><div className="space-y-2"><Label>Short description</Label><Input name="short_description" maxLength={280} required defaultValue={editing?.short_description || ""} /></div><div className="space-y-2"><Label>Description</Label><Textarea name="description" required defaultValue={editing?.description || ""} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Website</Label><Input name="website_url" type="url" defaultValue={editing?.website_url || ""} /></div><div className="space-y-2"><Label>Image path</Label><Input name="image_path" defaultValue={editing?.image_path || ""} placeholder="Uploaded path or public asset path" /></div></div><div className="flex flex-wrap gap-5 text-sm"><label className="flex items-center gap-2"><input type="checkbox" name="is_featured" defaultChecked={editing?.is_featured || false} /> Featured</label><label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={editing ? editing.is_active : true} /> Active</label></div><div className="flex gap-2"><Button type="submit">{editing ? "Save changes" : "Create charity"}</Button>{editing && <Button type="button" variant="outline" onClick={() => setEditingId(null)}>Clear</Button>}</div></form></CardContent></Card>
    <Card><CardHeader><CardTitle>Charity media</CardTitle><CardDescription>Upload a public image to the charity-media bucket.</CardDescription></CardHeader><CardContent><div className="space-y-4">{data.charities.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{c.name}</p><p className="text-xs text-muted-foreground">{c.image_path || "No image"}</p></div><form action={uploadCharityMediaAction} className="flex items-center gap-2"><input type="hidden" name="charity_id" value={c.id} /><Input name="file" type="file" accept="image/jpeg,image/png,image/webp" required className="max-w-56" /><Button size="sm" type="submit"><Upload className="mr-1 h-3.5 w-3.5" />Upload</Button></form></div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle>Charity directory</CardTitle><CardDescription>Activate/deactivate and edit existing charities.</CardDescription></CardHeader><CardContent className="space-y-3">{data.charities.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><div className="flex items-center gap-2"><p className="font-medium">{c.name}</p>{c.is_featured && <Badge>Featured</Badge>}<Badge variant={c.is_active ? "default" : "outline"}>{c.is_active ? "Active" : "Inactive"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{c.short_description}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditingId(c.id)}>Edit</Button><form action={setCharityActiveAction}><input type="hidden" name="charity_id" value={c.id} /><input type="hidden" name="active" value={String(!c.is_active)} /><Button size="sm" variant="outline" type="submit">{c.is_active ? "Deactivate" : "Activate"}</Button></form></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Upcoming events</CardTitle><CardDescription>Add or remove charity golf days and events.</CardDescription></CardHeader><CardContent className="space-y-4"><form action={createCharityEventAction} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-2"><div className="space-y-2"><Label>Charity</Label><select name="charity_id" required className="h-8 w-full rounded-lg border px-2 text-sm">{data.charities.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="space-y-2"><Label>Title</Label><Input name="title" required /></div><div className="space-y-2"><Label>Start</Label><Input name="starts_at" type="datetime-local" required /></div><div className="space-y-2"><Label>End</Label><Input name="ends_at" type="datetime-local" /></div><div className="space-y-2"><Label>Location</Label><Input name="location" /></div><div className="space-y-2"><Label>Registration URL</Label><Input name="registration_url" type="url" /></div><div className="sm:col-span-2 space-y-2"><Label>Description</Label><Textarea name="description" /></div><div className="sm:col-span-2"><Button type="submit"><CalendarDays className="mr-2 h-4 w-4" />Add event</Button></div></form>{data.events.map(e => <div key={e.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{e.title}</p><p className="text-sm text-muted-foreground">{data.charities.find(c => c.id === e.charity_id)?.name || "Charity"} · {date(e.starts_at)} · {e.location || "Location TBC"}</p></div><form action={deleteCharityEventAction}><input type="hidden" name="event_id" value={e.id} /><Button size="sm" variant="destructive" type="submit">Delete</Button></form></div>)}</CardContent></Card>
  </div>;
}

function WinnersPanel({ data }: { data: AdminData }) { return <Card><CardHeader><CardTitle>Winner verification & payouts</CardTitle><CardDescription>Review proof submissions, approve/reject winners and record payouts.</CardDescription></CardHeader><CardContent className="space-y-4">{data.winners.length === 0 ? <p className="text-sm text-muted-foreground">No winners yet.</p> : data.winners.map(w => <div key={w.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{w.tier}-match · {money(w.prize_amount_minor, w.currency)}</p><p className="mt-1 font-mono text-xs text-muted-foreground">Winner {w.user_id}</p>{w.winner_proofs && <p className="mt-2 text-sm">Proof: {Array.isArray(w.winner_proofs) ? w.winner_proofs.map(p => p.original_filename).join(", ") : w.winner_proofs.original_filename}</p>}</div><Badge variant={statusVariant(w.verification_status)}>{w.verification_status}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{["pending", "submitted", "under_review"].includes(w.verification_status) && <><form action={reviewWinnerAction}><input type="hidden" name="winner_id" value={w.id} /><input type="hidden" name="decision" value="approved" /><Button size="sm" type="submit">Approve</Button></form><form action={reviewWinnerAction} className="flex gap-2"><input type="hidden" name="winner_id" value={w.id} /><input type="hidden" name="decision" value="rejected" /><Input name="reason" placeholder="Rejection reason" required className="w-48" /><Button size="sm" variant="destructive" type="submit">Reject</Button></form></>}{w.verification_status === "approved" && <form action={markWinnerPaidAction} className="flex gap-2"><input type="hidden" name="winner_id" value={w.id} /><Input name="provider_reference" placeholder="Payment reference" className="w-48" /><Button size="sm" type="submit">Mark paid</Button></form>}{w.verification_status === "paid" && <span className="text-sm text-muted-foreground">Payout completed.</span>}</div></div>)}</CardContent></Card>; }
